# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deckk < Formula
  desc "Point a URL at it, get a PDF (pitch decks, docsend, etc.)"
  homepage "https://github.com/holman/deckk"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/holman/deckk/releases/download/v0.4.1/deckk_darwin_amd64.tar.gz"
      sha256 "b41d05d7f9fc3005ad78eee344efc000a65838702be34f69f8d2e12501156bca"

      define_method(:install) do
        bin.install "deckk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/holman/deckk/releases/download/v0.4.1/deckk_darwin_arm64.tar.gz"
      sha256 "85d3aad6a40ef0151caeb43f2ad7fa2c46ff4c500f339b0cd26efa83e7a29ea3"

      define_method(:install) do
        bin.install "deckk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/holman/deckk/releases/download/v0.4.1/deckk_linux_amd64.tar.gz"
      sha256 "6ae83a37f9840f15c8c48c5a03743840999bde8a1a0a02162f9596214bc9e74b"
      define_method(:install) do
        bin.install "deckk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/holman/deckk/releases/download/v0.4.1/deckk_linux_arm64.tar.gz"
      sha256 "dad4d4ce9e8aeee8c669604f41af5e0bcb8726236906a0de8b0df53fafd7f003"
      define_method(:install) do
        bin.install "deckk"
      end
    end
  end

  def caveats
    <<~EOS
      deckk drives a headless Chrome over the DevTools Protocol. If you
      don't already have Chrome installed:

        brew install --cask google-chrome
    EOS
  end

  test do
    system "#{bin}/deckk", "-h"
  end
end
